version: '3'
networks:
  BACKEND:
services:
  mongo:
    image: "mongo:5"
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: django
      MONGO_INITDB_ROOT_PASSWORD: django
    networks:
      BACKEND:
  mongo-express:
    image: mongo-express
    restart: "no"
    networks:
      BACKEND:
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: django
      ME_CONFIG_MONGODB_ADMINPASSWORD: django
      ME_CONFIG_MONGODB_URL: mongodb://django:django@mongo:27017/
  gunicorn:
    image: "onlinepayment_gunicorn:latest"
    restart: "no"
    environment:
      - MONGO_HOST=mongo
      - MONGO_USERNAME=django
      - MONGO_PASSWORD=django
    depends_on:
      - mongo
    networks:
      BACKEND:
    ports:
      - 8014:8000