# Generated by Django 4.0.2 on 2022-02-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Amount')),
                ('track_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Track ID')),
                ('request_result_code', models.CharField(help_text='IPG result code in response to our payment request', max_length=4, verbose_name='Request Result Code')),
                ('is_successful', models.BooleanField(blank=True, null=True, verbose_name='Is successful?')),
                ('payment_status_code', models.CharField(blank=True, help_text='IPG payment result code in response to our payment attempt.', max_length=4, null=True, verbose_name='Payment Status Code')),
                ('payed_amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Verified Payed Amount')),
                ('verification_status_code', models.CharField(blank=True, help_text='IPG payment verification result code in response to our payment verification attempt.', max_length=4, null=True, verbose_name='Payment Verification Status Code')),
                ('ref_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref. Number')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
