# Generated by Django 4.0.2 on 2022-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is verified?'),
        ),
    ]
